version: "3.8"

services:
  client:
    container_name: client-EGS
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host

  courier:
    container_name: courier-EGS
    build:
      context: ./courier
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./courier:/app
      - /app/node_modules
    command: npm run dev -- --host
